Only construct HttpClient once in the DownloadFromAzure task
This change modifies the DownloadFromAzure task by only constructing
the HttpClient once in ExecuteAsync and passing it to DownloadItem
instead of allocating it over and over again for each file; after
I checked in the compiled binary of CloudTestTasks with this fix
into ProjectN about 3 weeks back, we stopped seeing the occasional
failure when accessing the Azure storage:

System.Net.Http.HttpRequestException: An error occurred while
sending the request. ---> System.Net.WebException: Unable to connect
to the remote server ---> System.Net.Sockets.SocketException:
Only one usage of each socket address (protocol/network address/port)
is normally permitted 13.88.144.240:443

Thanks

Tomas